import { Category, Course, Instructor } from "@/types";

export const instructors: Instructor[] = [
  {
    id: "1",
    name: "Dr. Rajesh Sharma",
    avatar: "https://i.pravatar.cc/150?img=1",
    role: "Senior Professor, Computer Science",
    bio: "Dr. Sharma has over 15 years of experience teaching Computer Science at top Nepali universities. He specializes in algorithms, data structures, and machine learning.",
    courses: 12,
    students: 3200,
    rating: 4.8,
    social: {
      twitter: "https://twitter.com/rajeshsharma",
      linkedin: "https://linkedin.com/in/rajeshsharma",
      website: "https://rajeshsharma.com",
    },
  },
  {
    id: "2",
    name: "Sunita Adhikari",
    avatar: "https://i.pravatar.cc/150?img=5",
    role: "Full Stack Developer & Educator",
    bio: "Sunita is a seasoned web developer with expertise in modern JavaScript frameworks. She has worked with international clients and now teaches the next generation of Nepali developers.",
    courses: 8,
    students: 2800,
    rating: 4.7,
  },
  {
    id: "3",
    name: "Binod Thapa",
    avatar: "https://i.pravatar.cc/150?img=3",
    role: "Cybersecurity Specialist",
    bio: "With a background in network security for financial institutions, Binod brings real-world experience to his comprehensive cybersecurity courses.",
    courses: 5,
    students: 1900,
    rating: 4.9,
  },
  {
    id: "4",
    name: "Pramila Rai",
    avatar: "https://i.pravatar.cc/150?img=4",
    role: "Data Scientist",
    bio: "Pramila has worked with major tech companies in analyzing big data. Her courses focus on practical applications of data science in the Nepali context.",
    courses: 7,
    students: 2100,
    rating: 4.6,
  },
];

export const categories: Category[] = [
  {
    id: "cs",
    name: "Computer Science",
    icon: "cpu",
    courses: 42,
  },
  {
    id: "prog",
    name: "Programming",
    icon: "code",
    courses: 58,
  },
  {
    id: "web",
    name: "Web Development",
    icon: "globe",
    courses: 36,
  },
  {
    id: "data",
    name: "Data Science",
    icon: "bar-chart",
    courses: 24,
  },
  {
    id: "cyber",
    name: "Cybersecurity",
    icon: "shield",
    courses: 18,
  },
  {
    id: "mobile",
    name: "Mobile Development",
    icon: "smartphone",
    courses: 22,
  },
  {
    id: "design",
    name: "UI/UX Design",
    icon: "layout",
    courses: 16,
  },
  {
    id: "network",
    name: "Networking",
    icon: "wifi",
    courses: 15,
  },
];

export const courses: Course[] = [
  {
    id: "bsc-csit-1",
    title: "BSc CSIT: Introduction to Programming",
    description: "A comprehensive introduction to programming concepts for BSc CSIT students using C and C++.",
    image: "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2940&q=80",
    price: 3500,
    instructor: instructors[0],
    category: categories[1],
    level: "Beginner",
    language: "Both",
    duration: "10 weeks",
    lessons: 42,
    rating: 4.7,
    enrolledStudents: 842,
    featured: true,
    syllabus: [
      {
        title: "Introduction to Programming",
        duration: "2 weeks",
        topics: ["History of Programming", "Basic Concepts", "Setting up the Environment"],
      },
      {
        title: "C Programming Fundamentals",
        duration: "4 weeks",
        topics: ["Variables and Data Types", "Control Structures", "Functions", "Arrays and Pointers"],
      },
      {
        title: "Object-Oriented Programming with C++",
        duration: "4 weeks",
        topics: ["Classes and Objects", "Inheritance", "Polymorphism", "Exception Handling"],
      },
    ],
  },
  {
    id: "web-dev-1",
    title: "Modern Web Development: Full Stack Journey",
    description: "Master modern web technologies from HTML/CSS fundamentals to advanced React and Node.js applications.",
    image: "https://images.unsplash.com/photo-1547658719-da2b51169166?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2864&q=80",
    price: 6000,
    discountPrice: 4800,
    instructor: instructors[1],
    category: categories[2],
    level: "Intermediate",
    language: "English",
    duration: "12 weeks",
    lessons: 60,
    rating: 4.9,
    enrolledStudents: 1240,
    popular: true,
    syllabus: [
      {
        title: "Front-end Fundamentals",
        duration: "4 weeks",
        topics: ["HTML5", "CSS3", "JavaScript ES6+", "Responsive Design"],
      },
      {
        title: "React.js Deep Dive",
        duration: "4 weeks",
        topics: ["Components", "State Management", "Hooks", "Router", "API Integration"],
      },
      {
        title: "Back-end with Node.js",
        duration: "4 weeks",
        topics: ["Express.js", "RESTful APIs", "Authentication", "Database Integration", "Deployment"],
      },
    ],
  },
  {
    id: "cyber-1",
    title: "Cybersecurity Fundamentals for Nepali Organizations",
    description: "Learn practical cybersecurity skills tailored to the unique challenges faced by Nepali businesses and organizations.",
    image: "https://images.unsplash.com/photo-1614064641938-3bbee52942c7?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2940&q=80",
    price: 5500,
    instructor: instructors[2],
    category: categories[4],
    level: "Beginner",
    language: "Both",
    duration: "8 weeks",
    lessons: 32,
    rating: 4.8,
    enrolledStudents: 620,
    new: true,
  },
  {
    id: "data-1",
    title: "Data Science and Analysis with Python",
    description: "From statistical basics to machine learning models, master data science with practical examples relevant to the Nepali market.",
    image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2940&q=80",
    price: 7000,
    discountPrice: 5600,
    instructor: instructors[3],
    category: categories[3],
    level: "Intermediate",
    language: "English",
    duration: "10 weeks",
    lessons: 45,
    rating: 4.6,
    enrolledStudents: 520,
    featured: true,
  },
  {
    id: "bca-1",
    title: "BCA: Database Management Systems",
    description: "A comprehensive course on database concepts, design, and implementation for BCA students.",
    image: "https://images.unsplash.com/photo-1654277041218-84424c074e0b?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2940&q=80",
    price: 4000,
    instructor: instructors[0],
    category: categories[0],
    level: "Intermediate",
    language: "Both",
    duration: "8 weeks",
    lessons: 36,
    rating: 4.5,
    enrolledStudents: 780,
  },
  {
    id: "mobile-1",
    title: "Flutter Mobile App Development",
    description: "Learn to build cross-platform mobile apps for Android and iOS using Flutter and Dart.",
    image: "https://images.unsplash.com/photo-1565106430482-8f6e74349ca1?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2940&q=80",
    price: 5800,
    discountPrice: 4900,
    instructor: instructors[1],
    category: categories[5],
    level: "Intermediate",
    language: "English",
    duration: "9 weeks",
    lessons: 40,
    rating: 4.7,
    enrolledStudents: 480,
    popular: true,
  },
  {
    id: "design-1",
    title: "UI/UX Design Principles",
    description: "Master the fundamentals of user interface and experience design with practical projects.",
    image: "https://images.unsplash.com/photo-1581291518633-83b4ebd1d83e?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2940&q=80",
    price: 4500,
    instructor: instructors[1],
    category: categories[6],
    level: "Beginner",
    language: "English",
    duration: "6 weeks",
    lessons: 28,
    rating: 4.8,
    enrolledStudents: 390,
    new: true,
  },
  {
    id: "network-1",
    title: "Computer Networks for Computer Engineering",
    description: "A detailed course on computer networking concepts, protocols, and implementation.",
    image: "https://images.unsplash.com/photo-1544197150-b99a580bb7a8?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2940&q=80",
    price: 4200,
    instructor: instructors[2],
    category: categories[7],
    level: "Advanced",
    language: "Both",
    duration: "8 weeks",
    lessons: 35,
    rating: 4.6,
    enrolledStudents: 320,
  },
];

export const reviews = [
  {
    id: "1",
    user: {
      name: "Aarav Poudel",
      avatar: "https://i.pravatar.cc/150?img=10",
    },
    rating: 5,
    date: "March 15, 2024",
    comment: "Excellent course! The content is well-structured and the instructor explains complex concepts clearly. The mix of Nepali and English instruction really helped my understanding."
  },
  {
    id: "2",
    user: {
      name: "Priya Sharma",
      avatar: "https://i.pravatar.cc/150?img=11",
    },
    rating: 4,
    date: "March 10, 2024",
    comment: "Very practical course with good examples. The programming assignments were challenging but helped reinforce the concepts."
  },
  {
    id: "3",
    user: {
      name: "Bikash KC",
      avatar: "https://i.pravatar.cc/150?img=12",
    },
    rating: 5,
    date: "March 5, 2024",
    comment: "The course material is up-to-date and relevant to the Nepali tech industry. Great value for money!"
  },
  {
    id: "4",
    user: {
      name: "Sarita Thapa",
      avatar: "https://i.pravatar.cc/150?img=13",
    },
    rating: 4,
    date: "February 28, 2024",
    comment: "The instructor's teaching style is engaging and the course projects are well-designed. Would recommend to others."
  },
  {
    id: "5",
    user: {
      name: "Dipesh Gurung",
      avatar: "https://i.pravatar.cc/150?img=14",
    },
    rating: 5,
    date: "February 25, 2024",
    comment: "Best programming course I've taken so far. The hands-on exercises really helped cement my understanding."
  }
];
